export type Options = {
    max_seconds_ads: number,
    skip_ads_after: number[],
    chromePath: string,
    close_server_on_finish: boolean,
    no_visuals: boolean,
    headless: boolean,
    concurrency: number,
    concurrencyInterval: number,
    timeout: number,
    disable_proxy_tests: boolean,
    proxy_tests_headless: boolean,
    stop_spawning_on_overload: boolean,
    auto_skip_ads: boolean,
    server_port: number,
    default_proxy_protocol: string,
    kill_zombies: boolean,
};